// <auto-generated />
using System;
using CertificatesManager.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CertificatesManager.Migrations
{
    [DbContext(typeof(CertificatesManagerDBContext))]
    [Migration("20191218141951_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CertificatesManager.Models.CertificateDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Environment");

                    b.Property<DateTime>("From");

                    b.Property<string>("InstallationLink");

                    b.Property<string>("Issuer");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<string>("OtherInfos");

                    b.Property<string>("Password");

                    b.Property<string>("Purpose");

                    b.Property<string>("SerialNumber");

                    b.Property<string>("SubjectName");

                    b.Property<DateTime>("To");

                    b.HasKey("Id");

                    b.ToTable("CertificateDetails");
                });

            modelBuilder.Entity("CertificatesManager.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CertificateDetailId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CertificateDetailId");

                    b.ToTable("Server");
                });

            modelBuilder.Entity("CertificatesManager.Models.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CertificateDetailId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CertificateDetailId");

                    b.ToTable("System");
                });

            modelBuilder.Entity("CertificatesManager.Models.Server", b =>
                {
                    b.HasOne("CertificatesManager.Models.CertificateDetail")
                        .WithMany("Servers")
                        .HasForeignKey("CertificateDetailId");
                });

            modelBuilder.Entity("CertificatesManager.Models.System", b =>
                {
                    b.HasOne("CertificatesManager.Models.CertificateDetail")
                        .WithMany("Systems")
                        .HasForeignKey("CertificateDetailId");
                });
#pragma warning restore 612, 618
        }
    }
}
